use Dockerfile-specific ignore-file when present
wunderio/silta-cli pull request #71
Opened 2024-12-03 14:39 UTC by Jancis

2025-01-14 09:49 UTC, Rade333 requested changes

2025-01-14 09:49 UTC, Rade333 commented on cmd/ciImageBuild.go
> +		if _, err := os.Stat(fmt.Sprintf("%s.dockerignore", dockerfile)); err == nil {
I believe you are missing the buildPath here, this now looks for the file in project root.

2025-01-21 09:18 UTC, Jancis commented on cmd/ciImageBuild.go
> +		if _, err := os.Stat(fmt.Sprintf("%s.dockerignore", dockerfile)); err == nil {
The dockerfile is full path to actual dockerfile and the preferred .dockerignore file location now is `<dockerfile>.dockerfile`. I think this is correct? :thinking:

2025-01-24 10:30 UTC, Rade333 commented on cmd/ciImageBuild.go
> +		if _, err := os.Stat(fmt.Sprintf("%s.dockerignore", dockerfile)); err == nil {
Ah indeed, you are correct!

2025-01-24 11:24 UTC, Rade333 approved these changes
Tested, works

2025-01-27 12:55 UTC, merged