test connection after cloud login, remove failed release log
wunderio/silta-cli pull request #73
Opened 2024-12-17 22:18 UTC by Jancis

- Test connection after cloud login
- [chore] Remove release log

2025-01-09 12:20 UTC, Rade333 reviewed
The builds / tests fail at https://github.com/wunderio/silta-cli/actions/runs/12689356464, can you please either check those or verify that it's unrelated

2025-01-24 10:36 UTC, Rade333 requested changes
It seems the cloud login step now fails with this build: https://app.circleci.com/pipelines/github/wunderio/drupal-project-k8s/6713/workflows/b3876b97-4ed6-4977-a8fe-c023178de1d6/jobs/22113

2025-05-05 08:26 UTC, Rade333 requested changes
Build fails: https://app.circleci.com/pipelines/github/wunderio/drupal-project-k8s/6917/workflows/707f8867-5bda-4528-a27d-a343749ae164

2025-05-22 12:32 UTC, Jancis commented
Error fixed, retested and it works: https://app.circleci.com/pipelines/github/wunderio/drupal-project-k8s/6959/workflows/cafd5bac-31b2-4288-8909-a8ea43a98a58

2025-06-02 06:41 UTC, merged